### ISSUE TITLE
Angular Migration broken

### ISSUE THREAD

**Issue by elsasslegend** [rnadler/ng9-password-strength-bar#4]
While migrating to angular 12 we get : 
`Package "ng9-password-strength-bar" has an incompatible peer dependency to "@angular/core" (requires "^9.1.9" (extended), would install "12.0.3")
`
which causes the migration to fail.
Is it possible to allow angular versions over 9 as dependencies ?

Thanks

**Comment by rnadler** [comment]
I was able to successfully upgrade an Angular 9.1 project (with "ng9-password-strength-bar": "1.1.0")  to Angular 12 by adding the ```--force``` flag to each of the 10/11/12 ```ng update``` [commands](https://update.angular.io/?v=9.1-12.0). Got lots of warnings, but it worked.
